### ISSUE TITLE
Could not load 'plugins/bReports-1.5.8.jar'

### ISSUE THREAD

**Issue by Cyberuben** [codename-B/bReport#8]
Getting the following error on Spigot version 20140911a. I have seen this error a few times already but I can not seem to find out why it happens. 

```
[09:41:35] [Server thread/ERROR]: Could not load 'plugins/bReports-1.5.8.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.IllegalArgumentException: Plugin already initialized!
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:133) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:336) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:258) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugins(CraftServer.java:369) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at net.minecraft.server.v1_7_R4.DedicatedServer.init(DedicatedServer.java:152) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:458) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
Caused by: java.lang.IllegalArgumentException: Plugin already initialized!
    at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:122) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at de.bananaco.report.commands.Commands.<init>(Commands.java:32) ~[?:?]
    at de.bananaco.report.ReportPlugin.<init>(ReportPlugin.java:34) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
    at java.lang.Class.newInstance(Class.java:374) ~[?:1.7.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    ... 6 more
Caused by: java.lang.IllegalStateException: Initial initialization
    at org.bukkit.plugin.java.PluginClassLoader.initialize(PluginClassLoader.java:125) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at org.bukkit.plugin.java.JavaPlugin.<init>(JavaPlugin.java:66) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at de.bananaco.report.ReportPlugin.<init>(ReportPlugin.java:28) ~[?:?]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.7.0_65]
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57) ~[?:1.7.0_65]
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.7.0_65]
    at java.lang.reflect.Constructor.newInstance(Constructor.java:526) ~[?:1.7.0_65]
    at java.lang.Class.newInstance(Class.java:374) ~[?:1.7.0_65]
    at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:76) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:129) ~[spigot.jar:git-Spigot-1.7.9-R0.2-205-g2c31986]
    ... 6 more
```

The lines above this error are as following:

```
[09:41:34] [Server thread/INFO]: Starting minecraft server version 1.7.10
[09:41:34] [Server thread/INFO]: Loading properties
[09:41:34] [Server thread/INFO]: Default game type: SURVIVAL
[09:41:34] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-1.7.9-R0.2-205-g2c31986 (MC: 1.7.10) (Implementing API version 1.7.10-R0.1-SNAPSHOT)
[09:41:35] [Server thread/INFO]: Debug logging is disabled
[09:41:35] [Server thread/INFO]: Server Ping Player Sample Count: 12
[09:41:35] [Server thread/INFO]: Using 4 threads for Netty based IO
[09:41:35] [Server thread/INFO]: Generating keypair
[09:41:35] [Server thread/INFO]: Starting Minecraft server on *:25565
[09:41:35] [Server thread/WARN]: Plugin `Warning_System v1.0' uses the space-character (0x20) in its name `Warning System' - this is discouraged
[09:41:35] [Server thread/INFO]: Set PluginClassLoader as parallel capable
```

**Comment by keough99** [comment]
i had the same thing happen but the plugin may only be compatible with a specific version of minecraft

**Comment by Cyberuben** [comment]
Why did you just reply to an issue that is more than a year old?
